### PR TITLE
Only call close() in drop() if the connection exists

### PR DESCRIPTION
**Pull request by david-cliqz**
Test attached.

### CODE REVIEW

**Comment by ikuyamada** [comment]
@david-cliqz Merged. Thanks!

**Comment by david-cliqz** [comment]
@ikuyamada You're welcome. However, I just realized that I forgot to increase the version number. Do you have plans to do so & upload the new version to pypi anytime soon?

**Comment by ikuyamada** [comment]
@david-cliqz I have just released a new version 0.1.4 that includes your changes:
https://pypi.python.org/pypi/gsocketpool/0.1.4

**Comment by david-cliqz** [comment]
Great, thanks!

**Pull request merged**
